# Generated by Django 4.2.3 on 2023-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('amount_ram', models.PositiveSmallIntegerField()),
                ('amount_hdd', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('quantity_in_stock', models.PositiveSmallIntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'laptop',
                'verbose_name_plural': 'laptops',
            },
        ),
    ]
