# Generated by Django 4.2.3 on 2023-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_laptop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'get_latest_by': 'added_date', 'verbose_name': 'laptop', 'verbose_name_plural': 'laptops'},
        ),
        migrations.AlterField(
            model_name='laptop',
            name='release_year',
            field=models.PositiveSmallIntegerField(max_length=4),
        ),
    ]
