# Generated by Django 4.2.3 on 2023-10-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_laptop_amount_hdd_alter_laptop_amount_ram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='amount_hdd',
            new_name='amount_hdd_gb',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='amount_ram',
            new_name='amount_ram_gb',
        ),
    ]
