# Generated by Django 4.2.3 on 2023-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_rename_amount_hdd_laptop_amount_hdd_gb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=6000)),
                ('authors_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pub', 'published'), ('unpub', 'unpublished'), ('ban', 'banned')], default='pub', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_in', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('1', 'Animals'), ('2', 'Cars'), ('3', 'Programming'), ('4', 'Monitors')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'get_latest_by': 'added_date', 'ordering': ['-added_date'], 'verbose_name': 'laptop', 'verbose_name_plural': 'laptops'},
        ),
    ]
