# Generated by Django 4.2.3 on 2023-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_post_alter_laptop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(choices=[('AS', 'Asus'), ('AE', 'Apple'), ('LO', 'Lenovo'), ('DL', 'Dell')], max_length=256),
        ),
    ]
