# Generated by Django 4.2.3 on 2023-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_laptop_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'laptop', 'verbose_name_plural': 'laptops'},
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='added_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='amount_hdd_gb',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='amount_ram_gb',
        ),
        migrations.AddField(
            model_name='laptop',
            name='amount_hdd_mb',
            field=models.PositiveSmallIntegerField(default=1000, help_text='Capacity in MB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='amount_ram_mb',
            field=models.PositiveSmallIntegerField(default=8000, help_text='Capacity in MB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
